# Generated by Django 5.1.1 on 2026-06-21 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.CharField(default='Pink', help_text='e.g., Pink, Blue, Green', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='mrp',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum Retail Price', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='offer_details',
            field=models.CharField(blank=True, help_text='e.g., free-shipping, 50% offer from MRP', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('teething', 'Teething Toys'), ('bath', 'Bath Toys'), ('feeding', 'Feeding Accessories'), ('sensory', 'Sensory Learning'), ('play', 'Baby Play'), ('pet', 'Pet Toys'), ('kitchen', 'Kitchen Silicone')], default='educational', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Selling Price (e.g., 1089.34)', max_digits=8),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
