# Generated by Django 5.1.1 on 2026-06-24 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_order_options_remove_order_is_shipped_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shiprocket_order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shiprocket_shipment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderitems',
            name='product_color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
