# Generated by Django 5.1.1 on 2026-06-26 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_order_shiprocket_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shiprocket_awb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shiprocket_label_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shiprocket_tracking_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
