"""
Django settings for e_com_pro project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv()
# testing git 
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-testkey-1234567890abcdefg'
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

if os.environ.get("ENVIRONMENT") == "production":
    ALLOWED_HOSTS = ["learnmythos.app", "www.learnmythos.app", "143.110.182.223"]
    CSRF_TRUSTED_ORIGINS = ["https://learnmythos.app", "https://www.learnmythos.app"]
    DEBUG = False
else:
    ALLOWED_HOSTS = ["learnmythos.app", "143.110.182.223", "localhost", "127.0.0.1"]


# Application definition

INSTALLED_APPS = [
    'unfold',
    'unfold.contrib.filters',
    'unfold.contrib.forms',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    "whitenoise.runserver_nostatic",
    'django.contrib.staticfiles',
    'core.apps.CoreConfig',
    'cart.apps.CartConfig',
    "payment.apps.PaymentConfig",

    'allauth',
    'allauth.account',
    'allauth.socialaccount',

    'allauth.socialaccount.providers.google',
    'crispy_forms',
    "crispy_bootstrap5",

    "django_cleanup.apps.CleanupConfig",

]


CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"

CRISPY_TEMPLATE_PACK = "bootstrap5"



SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        }
    }
}



AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "allauth.account.middleware.AccountMiddleware",

]

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",  # Handles MEDIA files
    },


    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}

STATICFILES_STORAGE = "whitenoise.storage.CompressedStaticFilesStorage"


ROOT_URLCONF = 'e_com_pro.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                "cart.context_processor.cart"
            ],
        },
    },
]

WSGI_APPLICATION = 'e_com_pro.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

#

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'railway',
#         'USER': 'postgres',
#         'PASSWORD': 'cpOktqTjiVVuHPeEASHRzwFinxqWTMGk',
#         'HOST': 'shinkansen.proxy.rlwy.net',
#         'PORT': '28969',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [ BASE_DIR / "static"]

STATIC_ROOT = BASE_DIR / "staticfiles"
# STATICFILES_STORAGE = "whitenoise.storage.CompressedStaticFilesStorage"

MEDIA_URL = "/media/"


if os.environ.get('production', False):
    # This path should match the mount path you set in Railway
    MEDIA_ROOT = "/app/media"
else:
    # Local development media path
    MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SOCIALACCOUNT_LOGIN_ON_GET = True
ACCOUNT_LOGOUT_ON_GET = True  # This skips the confirmation step

# Allauth Email Authentication Settings
ACCOUNT_AUTHENTICATION_METHOD = "username_email"
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_EMAIL_VERIFICATION = "none" # Set to mandatory for production later

LOGIN_REDIRECT_URL = "home"
ACCOUNT_SIGNUP_REDIRECT_URL = "home"

ACCOUNT_LOGOUT_REDIRECT_URL = "account_login"


RAZOR_PAY_SECRET_KEY = os.environ.get("RAZORPAY_SECRET_KEY", "")
RAZOR_PAY_KEY_ID = os.environ.get("RAZORPAY_KEY_ID", "")

RAZOR_PAY_CALLBACK_URL = "payment_verify"


# Add these to your Django settings.py
if os.environ.get("ENVIRONMENT") == 'production':
    SECURE_SSL_REDIRECT = True  # Redirects all HTTP requests to HTTPS
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True


WHITENOISE_AUTOREFRESH = True
WHITENOISE_USE_FINDERS = True


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'django.log'),
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],  # Log to both console and file
            'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO'),
            'propagate': True,
        },
    },
}

# ─────────────────────────────────────────────
# UNFOLD ADMIN PANEL SETTINGS — Premium Command Center
# ─────────────────────────────────────────────
from django.urls import reverse_lazy


def get_dashboard_callback(request, context):
    """Inject KPI data into the admin dashboard."""
    from django.utils import timezone
    from datetime import timedelta
    try:
        from payment.models import Order
        from core.models import Product, CustomerForm, Review
        from django.contrib.auth import get_user_model

        today    = timezone.now().date()
        week_ago = today - timedelta(days=7)
        User     = get_user_model()

        orders_all   = Order.objects.filter(is_paid=True)
        orders_today = orders_all.filter(ordered_date__date=today)
        orders_week  = orders_all.filter(ordered_date__date__gte=week_ago)

        revenue_today = sum(float(o.amount_paid or 0) for o in orders_today)
        revenue_week  = sum(float(o.amount_paid or 0) for o in orders_week)
        cnt_week      = orders_week.count()
        aov           = revenue_week / cnt_week if cnt_week > 0 else 0

        context.update({
            "kpi_orders_today":    orders_today.count(),
            "kpi_revenue_today":   f"\u20b9{revenue_today:,.0f}",
            "kpi_revenue_week":    f"\u20b9{revenue_week:,.0f}",
            "kpi_pending":         orders_all.filter(status="Pending").count(),
            "kpi_processing":      orders_all.filter(status="Processing").count(),
            "kpi_shipped":         orders_all.filter(status="Shipped").count(),
            "kpi_aov":             f"\u20b9{aov:,.0f}",
            "kpi_low_stock":       Product.objects.filter(stock__lte=5, is_active=True),
            "kpi_new_enquiries":   CustomerForm.objects.order_by("-created_at")[:5],
            "kpi_new_reviews":     Review.objects.order_by("-created_at")[:5],
            "kpi_latest_orders":   orders_all.order_by("-ordered_date")[:8],
            "kpi_top_products":    Product.objects.filter(is_active=True).order_by("-no_of_sales")[:5],
            "kpi_total_products":  Product.objects.filter(is_active=True).count(),
            "kpi_total_customers": User.objects.count(),
        })
    except Exception:
        pass
    return context


UNFOLD = {
    "SITE_TITLE":  "Fimiku Command Center",
    "SITE_HEADER": "Fimiku",
    "SITE_URL":    "/",
    "SITE_SYMBOL": "storefront",
    "SHOW_HISTORY":      True,
    "SHOW_VIEW_ON_SITE": True,
    "DASHBOARD_CALLBACK": "e_com_pro.settings.get_dashboard_callback",
    "STYLES":  ["/static/css/admin_premium.css"],
    "SCRIPTS": ["/static/js/admin_premium.js"],
    "COLORS": {
        "primary": {
            "50":  "245 243 255",
            "100": "237 233 254",
            "200": "221 214 254",
            "300": "196 181 253",
            "400": "167 139 250",
            "500": "139 92 246",
            "600": "124 58 237",
            "700": "109 40 217",
            "800": "91 33 182",
            "900": "76 29 149",
            "950": "46 16 101",
        },
    },
    "SIDEBAR": {
        "show_search":           True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": "Dashboard",
                "separator": False,
                "items": [
                    {
                        "title": "Overview",
                        "icon":  "dashboard",
                        "link":  reverse_lazy("admin:index"),
                    },
                    {
                        "title": "Order Dashboard",
                        "icon":  "receipt_long",
                        "link":  reverse_lazy("order_dashboard"),
                    },
                ],
            },
            {
                "title": "Store",
                "separator": True,
                "items": [
                    {
                        "title": "Products",
                        "icon":  "inventory_2",
                        "link":  reverse_lazy("admin:core_product_changelist"),
                        "badge": "core.admin.product_count_badge",
                    },
                    {
                        "title": "Reviews",
                        "icon":  "star",
                        "link":  reverse_lazy("admin:core_review_changelist"),
                    },
                    {
                        "title": "Wishlists",
                        "icon":  "favorite",
                        "link":  reverse_lazy("admin:core_wishlist_changelist"),
                    },
                ],
            },
            {
                "title": "Sales",
                "separator": True,
                "items": [
                    {
                        "title": "All Orders",
                        "icon":  "shopping_cart",
                        "link":  reverse_lazy("admin:payment_order_changelist"),
                        "badge": "core.admin.pending_orders_badge",
                    },
                    {
                        "title": "Order Items",
                        "icon":  "list_alt",
                        "link":  reverse_lazy("admin:payment_orderitems_changelist"),
                    },
                    {
                        "title": "Shipping Addresses",
                        "icon":  "local_shipping",
                        "link":  reverse_lazy("admin:payment_shippingaddress_changelist"),
                    },
                ],
            },
            {
                "title": "Customers",
                "separator": True,
                "items": [
                    {
                        "title": "Users",
                        "icon":  "group",
                        "link":  reverse_lazy("admin:auth_user_changelist"),
                    },
                    {
                        "title": "Enquiries",
                        "icon":  "mail",
                        "link":  reverse_lazy("admin:core_customerform_changelist"),
                        "badge": "core.admin.enquiry_count_badge",
                    },
                ],
            },
        ],
    },



# Email Configuration
if os.environ.get("ENVIRONMENT") == "production":
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = 'smtp.gmail.com'
    EMAIL_PORT = 587
    EMAIL_USE_TLS = True
    EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER")
    EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD")
    ADMIN_EMAIL = os.environ.get("ADMIN_EMAIL", EMAIL_HOST_USER)
else:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    EMAIL_HOST_USER = 'local@fimiku.com'
    ADMIN_EMAIL = 'admin@fimiku.com'